# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_auto_20170217_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlist',
            unique_together=set([('percent', 'probability')]),
        ),
    ]
