# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 12:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_auto_20170217_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlist',
            name='fine',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Премия'),
        ),
    ]
