# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 05:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0005_actionlist_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlist',
            name='fine',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Штраф'),
        ),
    ]
