# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestedCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='conditionalprofit',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
