# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20170206_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalprofit',
            name='conditionalProfit',
            field=models.FloatField(default=0, verbose_name='Прибль в %'),
        ),
    ]
