# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 05:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkansas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0)),
                ('yearRevenue', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ежегодный доход до расширения')),
                ('ExpectRevenue', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ожидаемый доход в течении года')),
                ('CostBuild', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Затраты на строительство')),
                ('year', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Период до расширения')),
                ('costEx', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Затраты на расширения')),
                ('cp', models.FloatField(default=0, verbose_name='Прибль в $')),
            ],
        ),
        migrations.AlterField(
            model_name='actionlist',
            name='costEx',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Затраты на расширения'),
        ),
        migrations.AddField(
            model_name='conditionalprofit',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkansas.ActionList'),
        ),
        migrations.AddField(
            model_name='conditionalprofit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkansas.EventList'),
        ),
    ]
