# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 06:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkansas', '0004_auto_20170303_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlist',
            name='year',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Количество лет до расширения!'),
        ),
        migrations.AlterField(
            model_name='conditionalprofit',
            name='year',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Период до расширения'),
        ),
    ]
