# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 06:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkansas', '0006_auto_20170303_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение колечества лет основного периода')),
            ],
        ),
    ]
