# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170202_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalprofit',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
