# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 02:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conditionalprofit_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionalprofit',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='conditionalprofit',
            name='profit',
        ),
        migrations.AddField(
            model_name='conditionalprofit',
            name='prize',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='conditionalprofit',
            name='fine',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
