# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_conditionalprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalprofit',
            name='conditionalProfit',
            field=models.FloatField(default=0),
        ),
    ]
