# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_conditionalprofit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlist',
            unique_together=set([('event', 'probability', 'action')]),
        ),
    ]
