# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 05:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalprofit',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='conditionalprofit',
            name='expence',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Издержки'),
        ),
        migrations.AlterField(
            model_name='conditionalprofit',
            name='revenue',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доход'),
        ),
    ]
